[package]
name = "myh"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version="1.2.2", features=["v4"], optional = true }

[[example]]
name = "features"
path = "examples/features.rs"
required-features = ["all"]


[features]
default = []
all = ["uuid"]
uuid = ["dep:uuid"]

